import { readFileSync } from "node:fs";

const VENDOR_JS = readFileSync(
  new URL("./vendor/wordcloud2.js", import.meta.url),
  "utf8",
);

export type RenderInput = {
  topUser: Array<[string, number]>;
  topClaude: Array<[string, number]>;
  meta: {
    sessions: number;
    messages: number;
    dateRange: [string, string] | null;
  };
};

function safeJson(value: unknown): string {
  return JSON.stringify(value).replace(/<\/(script)/gi, "<\\/$1");
}

function formatSubhead(meta: RenderInput["meta"]): string {
  const range = meta.dateRange
    ? ` · ${meta.dateRange[0]} → ${meta.dateRange[1]}`
    : "";
  const sNoun = meta.sessions === 1 ? "session" : "sessions";
  const mNoun = meta.messages === 1 ? "message" : "messages";
  return `${meta.sessions} ${sNoun} · ${meta.messages} ${mNoun}${range}`;
}

export function renderHtml(input: RenderInput): string {
  const dataJson = safeJson({
    topUser: input.topUser,
    topClaude: input.topClaude,
    meta: input.meta,
  });
  const subhead = formatSubhead(input.meta);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>OK Claude</title>
<style>
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: #0b0d10; color: #e7eaee; font-family: system-ui, -apple-system, "Segoe UI", sans-serif; }
  header { padding: 1.5rem 2rem 0.5rem; }
  header h1 { margin: 0; font-size: 1.75rem; font-weight: 700; letter-spacing: -0.02em; }
  header p { margin: 0.25rem 0 0; color: #8a939b; font-size: 0.95rem; }
  main { padding: 1rem 2rem 2rem; }
  #cloud-wrap { width: 100%; aspect-ratio: 16 / 10; max-height: calc(100vh - 9rem); background: #11141a; border-radius: 12px; overflow: hidden; }
  #cloud { width: 100%; height: 100%; display: block; }
  footer { padding: 0 2rem 1.5rem; color: #5b6168; font-size: 0.8rem; }
  footer a { color: inherit; }
</style>
</head>
<body>
<header>
  <h1>OK Claude</h1>
  <p>${subhead}</p>
</header>
<main>
  <div id="cloud-wrap"><canvas id="cloud"></canvas></div>
</main>
<footer>generated by <code>npx ok-claude</code> · mechanical word frequency · all rendering offline</footer>

<script>window.__DATA__ = ${dataJson};</script>
<script>
${VENDOR_JS}
</script>
<script>
(function boot() {
  var data = window.__DATA__;
  var list = (data && Array.isArray(data.topUser)) ? data.topUser : [];
  if (list.length === 0) {
    document.getElementById('cloud-wrap').innerHTML = '<p style="padding:2rem;color:#8a939b">No words to render.</p>';
    return;
  }
  var canvas = document.getElementById('cloud');
  function resize() {
    var wrap = document.getElementById('cloud-wrap');
    var dpr = window.devicePixelRatio || 1;
    canvas.width = wrap.clientWidth * dpr;
    canvas.height = wrap.clientHeight * dpr;
    canvas.style.width = wrap.clientWidth + 'px';
    canvas.style.height = wrap.clientHeight + 'px';
  }
  resize();
  var max = list[0][1];
  var weighted = list.map(function (pair) {
    var ratio = pair[1] / max;
    var size = 12 + Math.round(ratio * 80);
    return [pair[0], size];
  });
  WordCloud(canvas, {
    list: weighted,
    gridSize: 8,
    rotateRatio: 0.25,
    rotationSteps: 2,
    backgroundColor: '#11141a',
    color: 'random-light',
    fontFamily: 'system-ui, -apple-system, "Segoe UI", sans-serif',
    shrinkToFit: true,
    drawOutOfBound: false,
  });
})();
</script>
</body>
</html>
`;
}
