import { readFileSync } from "node:fs";

const VENDOR_JS = readFileSync(
  new URL("./vendor/wordcloud2.js", import.meta.url),
  "utf8",
);

export type OpenerEntry = { display: string; count: number };

export type RenderInput = {
  topUser: Array<[string, number]>;
  topClaude: Array<[string, number]>;
  openersUser: OpenerEntry[];
  openersClaude: OpenerEntry[];
  meta: {
    sessions: number;
    messages: number;
    tokensIn: number;
    tokensOut: number;
    dateRange: [string, string] | null;
  };
};

function safeJson(value: unknown): string {
  return JSON.stringify(value).replace(/<\/(script)/gi, "<\\/$1");
}

function formatTokens(total: number): string {
  if (total >= 1_000_000) return `${(total / 1_000_000).toFixed(1)}M`;
  if (total >= 1_000) return `${(total / 1_000).toFixed(1)}K`;
  return String(total);
}

function formatSubhead(meta: RenderInput["meta"]): string {
  const range = meta.dateRange
    ? ` · ${meta.dateRange[0]} → ${meta.dateRange[1]}`
    : "";
  const sNoun = meta.sessions === 1 ? "session" : "sessions";
  const mNoun = meta.messages === 1 ? "message" : "messages";
  const totalTokens = meta.tokensIn + meta.tokensOut;
  const tokens =
    totalTokens > 0 ? `${formatTokens(totalTokens)} tokens · ` : "";
  return `${tokens}${meta.sessions} ${sNoun} · ${meta.messages} ${mNoun}${range}`;
}

export function renderHtml(input: RenderInput): string {
  const dataJson = safeJson({
    topUser: input.topUser,
    topClaude: input.topClaude,
    openersUser: input.openersUser,
    openersClaude: input.openersClaude,
    meta: input.meta,
  });
  const subhead = formatSubhead(input.meta);

  return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8" />
<title>OK Claude</title>
<style>
  * { box-sizing: border-box; }
  html, body { margin: 0; padding: 0; background: #0b0d10; color: #e7eaee; font-family: system-ui, -apple-system, "Segoe UI", sans-serif; }
  header { padding: 1.5rem 2rem 0.5rem; }
  header h1 { margin: 0; font-size: 1.75rem; font-weight: 700; letter-spacing: -0.02em; }
  header p { margin: 0.25rem 0 0; color: #8a939b; font-size: 0.95rem; }
  main { padding: 1rem 2rem 2rem; }
  #tabs { display: flex; gap: 0.5rem; margin-bottom: 0.75rem; }
  #tabs button { appearance: none; background: #11141a; color: #8a939b; border: 1px solid #1d2330; border-radius: 8px; padding: 0.45rem 1rem; font: inherit; cursor: pointer; transition: background 120ms, color 120ms, border-color 120ms; }
  #tabs button:hover { color: #e7eaee; }
  #tabs button.active { background: #1d2330; color: #e7eaee; border-color: #2a3242; }
  #board { display: flex; gap: 1rem; align-items: stretch; }
  #cloud-wrap { flex: 1 1 auto; aspect-ratio: 16 / 10; max-height: calc(100vh - 12rem); background: #11141a; border-radius: 12px; overflow: hidden; position: relative; }
  #cloud { width: 100%; height: 100%; display: block; }
  #openers { flex: 0 0 200px; background: #11141a; border-radius: 12px; padding: 0.75rem 1rem; overflow: hidden; }
  #openers h2 { margin: 0 0 0.5rem; font-size: 0.85rem; font-weight: 600; color: #8a939b; text-transform: uppercase; letter-spacing: 0.05em; }
  #opener-list { list-style: none; margin: 0; padding: 0; display: flex; flex-direction: column; gap: 0.35rem; }
  #opener-list li { display: flex; justify-content: space-between; align-items: baseline; font-size: 0.95rem; color: #e7eaee; }
  #opener-list .count { color: #5b6168; font-variant-numeric: tabular-nums; }
  #opener-list .empty { color: #5b6168; font-style: italic; }
  footer { padding: 0 2rem 1.5rem; color: #5b6168; font-size: 0.8rem; }
  footer a { color: inherit; }
  @media (max-width: 640px) {
    #board { flex-direction: column; }
    #openers { flex: 0 0 auto; }
  }
</style>
</head>
<body>
<header>
  <h1>OK Claude</h1>
  <p>${subhead}</p>
</header>
<main>
  <div id="tabs">
    <button type="button" data-tab="user" class="active">You</button>
    <button type="button" data-tab="claude">Claude</button>
  </div>
  <div id="board">
    <div id="cloud-wrap"><canvas id="cloud"></canvas></div>
    <aside id="openers">
      <h2>Openers</h2>
      <ol id="opener-list"></ol>
    </aside>
  </div>
</main>
<footer>generated by <code>npx ok-claude</code> · mechanical word frequency · all rendering offline</footer>

<script>window.__DATA__ = ${dataJson};</script>
<script>
${VENDOR_JS}
</script>
<script>
(function boot() {
  var data = window.__DATA__ || { topUser: [], topClaude: [], openersUser: [], openersClaude: [], meta: {} };
  var lists = { user: data.topUser || [], claude: data.topClaude || [] };
  var openers = { user: data.openersUser || [], claude: data.openersClaude || [] };
  var canvas = document.getElementById('cloud');
  var wrap = document.getElementById('cloud-wrap');
  var active = 'user';

  function resize() {
    var dpr = window.devicePixelRatio || 1;
    canvas.width = wrap.clientWidth * dpr;
    canvas.height = wrap.clientHeight * dpr;
    canvas.style.width = wrap.clientWidth + 'px';
    canvas.style.height = wrap.clientHeight + 'px';
  }

  function showEmpty(tab) {
    var msg = tab === 'user' ? 'No words from You yet.' : 'No words from Claude yet.';
    wrap.innerHTML = '<p style="padding:2rem;color:#8a939b">' + msg + '</p>';
  }

  function restoreCanvas() {
    if (!document.getElementById('cloud')) {
      wrap.innerHTML = '<canvas id="cloud"></canvas>';
      canvas = document.getElementById('cloud');
    }
  }

  function draw(tab) {
    var list = lists[tab];
    if (!list.length) {
      showEmpty(tab);
      return;
    }
    restoreCanvas();
    resize();
    var max = list[0][1];
    var weighted = list.map(function (pair) {
      var ratio = pair[1] / max;
      var size = 12 + Math.round(ratio * 80);
      return [pair[0], size];
    });
    WordCloud(canvas, {
      list: weighted,
      gridSize: 8,
      rotateRatio: 0.25,
      rotationSteps: 2,
      backgroundColor: '#11141a',
      color: 'random-light',
      fontFamily: 'system-ui, -apple-system, "Segoe UI", sans-serif',
      shrinkToFit: true,
      drawOutOfBound: false,
    });
  }

  function paintOpeners(tab) {
    var list = openers[tab];
    var ol = document.getElementById('opener-list');
    if (!ol) return;
    if (!list.length) {
      ol.innerHTML = '<li class="empty">No openers yet.</li>';
      return;
    }
    var html = '';
    for (var i = 0; i < list.length; i++) {
      html += '<li><span class="word"></span><span class="count"></span></li>';
    }
    ol.innerHTML = html;
    var lis = ol.querySelectorAll('li');
    for (var j = 0; j < list.length; j++) {
      lis[j].querySelector('.word').textContent = list[j].display;
      lis[j].querySelector('.count').textContent = list[j].count;
    }
  }

  function setActive(tab) {
    active = tab;
    var buttons = document.querySelectorAll('#tabs button');
    for (var i = 0; i < buttons.length; i++) {
      var btn = buttons[i];
      if (btn.getAttribute('data-tab') === tab) btn.classList.add('active');
      else btn.classList.remove('active');
    }
    draw(tab);
    paintOpeners(tab);
  }

  document.getElementById('tabs').addEventListener('click', function (ev) {
    var t = ev.target;
    if (!t || t.tagName !== 'BUTTON') return;
    var tab = t.getAttribute('data-tab');
    if (!tab || tab === active || !lists[tab]) return;
    setActive(tab);
  });

  setActive('user');
})();
</script>
</body>
</html>
`;
}
